### ISSUE TITLE
support hide the cloze text in exported pdf

### ISSUE THREAD

**Issue by zhuoqiang** [DearVikki/obsidian-cloze-plugin#2]
thanks for sharing cloze plugin, it is quite useful. 

It would be great to hide the cloze text in the exported pdf file as well.

I find it could be done by defining the following css

```css
.cloze-span {
  position: relative;
}

.cloze-span::after {
  content: "_";
  position: absolute;
  top: 0;
  left: 0;
  background-color: white;
  /* background-color: var(--parent-background-color); */
}
```

maybe it could be build into cloze in someway.
