### ISSUE TITLE
关于填空样式的问题

### ISSUE THREAD

**Issue by itsdrchen** [DearVikki/obsidian-cloze-plugin#22]
请问如何实现您那样的填空位置是块状的带颜色的遮盖呢？CSS样式里好像无法修改这个？谢谢

**Comment by DearVikki** [comment]
@itsdrchen hi, 也是使用的一款高亮插件 Highlightr

**Comment by itsdrchen** [comment]
谢谢回复，高亮可以理解，关键是您的插件“填空”这个功能好像只能是以下划线的形式表现？不知道这种色块遮盖的方法是如何实现的？非常感谢！插件很好用！

**Comment by DearVikki** [comment]
哈哈谢谢~ @itsdrchen 哈哈哈自定义填空确实默认是加下划线，你看到的我色块遮盖的例子，正是由于那是从高亮转换的填空（即原文就是高亮），所以填空上才会有高亮。

而如果你想给自定义填空加带颜色的遮盖，可以试试这个自定义CSS：

```css
.cloze-span {
    background-color: pink; /* 或任何其他颜色 */
}
```
