### ISSUE TITLE
[Suggestions] Add an option to customize cloze appearance when set on "fixed length"

### ISSUE THREAD

**Issue by tiovialde** [DearVikki/obsidian-cloze-plugin#31]
Thanks for a cool plugin that makes it easier to present material in Obsidian.

I was wondering that it would be nice to be given an option to specify what the clozes look like with fixed length. Currently they look like this:
Hello ___! -> Hello [World]!

I think it might be nice to be able to change what is presented

**Comment by DearVikki** [comment]
Hi @tiovialde, yes it would be nice to customize the cloze style! 

Here's a little trick for you, try add this code snippet in Obsidian custom CSS:

```css
.cloze-fixed-width .cloze {
    border-bottom: none !important;
}

.cloze-fixed-width .cloze::before {
    content: "[";
    position: absolute;
    color: var(--text-normal);
    left: 0;
    top: 2px;
}

.cloze-fixed-width .cloze::after {
    content: "]";
    position: absolute;
    color: var(--text-normal);
    right: 0;
    top: 2px;
}
```
Hope it can meet your needs. 😃
